import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";
import { defineConfig, globalIgnores } from "eslint/config";
import eslintConfigPrettier from "eslint-config-prettier/flat";
import pluginQuery from "@tanstack/eslint-plugin-query";

export default defineConfig([
  globalIgnores([
    "dist",
    "src/deprecated", // excluded from tsconfig
    "src/routeTree.gen.ts", // generated by @tanstack/router-plugin
    "src/supabase/db_types.ts", // generated by supabase gen types
    "src/supabase/messages-v0.ts", // legacy v0 compat module (@ts-nocheck'd)
    "vite.config.ts",
    "eslint.config.js",
  ]),
  ...pluginQuery.configs["flat/recommended"],
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      // Type-aware "recommended" tier (per VITE.md). `strictTypeChecked` was the
      // template's stricter option but was never actually enforced.
      tseslint.configs.recommendedTypeChecked,
      reactHooks.configs["recommended-latest"],
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
      // Type-aware linting: resolve the project per file via the TS project
      // service (uses ./tsconfig.json, include "src").
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  eslintConfigPrettier,
  reactRefresh.configs.vite,
  {
    // Project rule policy — applied last so it overrides the configs above.
    files: ["**/*.{ts,tsx}"],
    rules: {
      // Route files intentionally export both `Route` and the component.
      "react-refresh/only-export-components": "off",

      // Keep ts-directives, but require a reason.
      "@typescript-eslint/ban-ts-comment": [
        "error",
        { "ts-expect-error": "allow-with-description" },
      ],

      // Allow the short-circuit / ternary side-effect idiom (`cond && fn()`)
      // while still catching genuinely dead statements.
      "@typescript-eslint/no-unused-expressions": [
        "error",
        { allowShortCircuit: true, allowTernary: true },
      ],

      // Allow interpolating numbers/booleans/nullish in template strings;
      // still flags objects/arrays.
      "@typescript-eslint/restrict-template-expressions": [
        "error",
        {
          allowNumber: true,
          allowBoolean: true,
          allowNullish: true,
          allowRegExp: true,
        },
      ],

      // Keep the real promise checks, drop the async-event-handler noise.
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: false },
      ],

      // `any`-tolerant boundaries (e.g. untyped function invocations): keep
      // visible as warnings rather than build-breaking errors.
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unsafe-assignment": "warn",
      "@typescript-eslint/no-unsafe-member-access": "warn",
      "@typescript-eslint/no-unsafe-call": "warn",
      "@typescript-eslint/no-unsafe-return": "warn",
      "@typescript-eslint/no-unsafe-argument": "warn",
      "@typescript-eslint/no-floating-promises": "warn",

      // React itself ships this as a warning; mirror it for the query plugin.
      "react-hooks/exhaustive-deps": "warn",
      "@tanstack/query/exhaustive-deps": "warn",

      // Cleanliness rule whose autofix is unsafe here (it removed a load-bearing
      // assertion and broke a comparison); several assertions are intentional.
      "@typescript-eslint/no-unnecessary-type-assertion": "off",

      // tsc's noUnusedLocals/noUnusedParameters is the enforced source of truth
      // (and passes); keep ESLint's stricter edge cases as warnings.
      "@typescript-eslint/no-unused-vars": "warn",

      // TanStack Router throws redirect()/notFound() objects by design; this
      // rule only produces false positives in a router app.
      "@typescript-eslint/only-throw-error": "off",
    },
  },
]);
