export const AVATAR_COLORS = [
  "emerald",
  "red",
  "teal",
  "amber",
  "cyan",
  "orange",
  "sky",
  "blue",
  "yellow",
  "lime",
  "green",
  "indigo",
  "violet",
  "purple",
  "fuchsia",
  "pink",
  "rose",
  "slate",
  "gray",
  "zinc",
  "neutral",
  "stone",
] as const;

export type AvatarColor = (typeof AVATAR_COLORS)[number];

export const AVATAR_TEXT_COLORS: Record<string, string> = {
  emerald: "text-emerald-700",
  red: "text-red-700",
  teal: "text-teal-700",
  amber: "text-amber-700",
  cyan: "text-cyan-700",
  orange: "text-orange-700",
  sky: "text-sky-700",
  blue: "text-blue-700",
  yellow: "text-yellow-700",
  lime: "text-lime-700",
  green: "text-green-700",
  indigo: "text-indigo-700",
  violet: "text-violet-700",
  purple: "text-purple-700",
  fuchsia: "text-fuchsia-700",
  pink: "text-pink-700",
  rose: "text-rose-700",
  slate: "text-slate-700",
  gray: "text-gray-700",
  zinc: "text-zinc-700",
  neutral: "text-neutral-700",
  stone: "text-stone-700",
};

export const AVATAR_BG_COLORS: Record<string, string> = {
  emerald: "bg-emerald-100",
  red: "bg-red-100",
  teal: "bg-teal-100",
  amber: "bg-amber-100",
  cyan: "bg-cyan-100",
  orange: "bg-orange-100",
  sky: "bg-sky-100",
  blue: "bg-blue-100",
  yellow: "bg-yellow-100",
  lime: "bg-lime-100",
  green: "bg-green-100",
  indigo: "bg-indigo-100",
  violet: "bg-violet-100",
  purple: "bg-purple-100",
  fuchsia: "bg-fuchsia-100",
  pink: "bg-pink-100",
  rose: "bg-rose-100",
  slate: "bg-slate-100",
  gray: "bg-gray-100",
  zinc: "bg-zinc-100",
  neutral: "bg-neutral-100",
  stone: "bg-stone-100",
};
