/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthIntegrationsIndexRouteImport } from './routes/_auth/integrations/index'
import { Route as AuthConversationsIndexRouteImport } from './routes/_auth/conversations/index'
import { Route as AuthContactsIndexRouteImport } from './routes/_auth/contacts/index'
import { Route as AuthAgentsIndexRouteImport } from './routes/_auth/agents/index'
import { Route as AuthIntegrationsMediaPreprocessingRouteImport } from './routes/_auth/integrations/media-preprocessing'
import { Route as AuthConversationsNewRouteImport } from './routes/_auth/conversations/new'
import { Route as AuthContactsNewRouteImport } from './routes/_auth/contacts/new'
import { Route as AuthContactsContactIdRouteImport } from './routes/_auth/contacts/$contactId'
import { Route as AuthAgentsNewRouteImport } from './routes/_auth/agents/new'
import { Route as AuthAgentsAgentIdRouteImport } from './routes/_auth/agents/$agentId'
import { Route as AuthSettingsWebhooksIndexRouteImport } from './routes/_auth/settings/webhooks/index'
import { Route as AuthSettingsOrganizationIndexRouteImport } from './routes/_auth/settings/organization/index'
import { Route as AuthSettingsMembersIndexRouteImport } from './routes/_auth/settings/members/index'
import { Route as AuthSettingsApiKeysIndexRouteImport } from './routes/_auth/settings/api-keys/index'
import { Route as AuthIntegrationsWhatsappIndexRouteImport } from './routes/_auth/integrations/whatsapp/index'
import { Route as AuthSettingsWebhooksNewRouteImport } from './routes/_auth/settings/webhooks/new'
import { Route as AuthSettingsWebhooksWebhookIdRouteImport } from './routes/_auth/settings/webhooks/$webhookId'
import { Route as AuthSettingsOrganizationNewRouteImport } from './routes/_auth/settings/organization/new'
import { Route as AuthSettingsMembersNewRouteImport } from './routes/_auth/settings/members/new'
import { Route as AuthSettingsMembersMemberIdRouteImport } from './routes/_auth/settings/members/$memberId'
import { Route as AuthSettingsApiKeysNewRouteImport } from './routes/_auth/settings/api-keys/new'
import { Route as AuthSettingsApiKeysApiKeyIdRouteImport } from './routes/_auth/settings/api-keys/$apiKeyId'
import { Route as AuthIntegrationsWhatsappNewRouteImport } from './routes/_auth/integrations/whatsapp/new'
import { Route as AuthIntegrationsWhatsappOrgAddressIdRouteImport } from './routes/_auth/integrations/whatsapp/$orgAddressId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIntegrationsIndexRoute = AuthIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConversationsIndexRoute = AuthConversationsIndexRouteImport.update({
  id: '/conversations/',
  path: '/conversations/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContactsIndexRoute = AuthContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsIndexRoute = AuthAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIntegrationsMediaPreprocessingRoute =
  AuthIntegrationsMediaPreprocessingRouteImport.update({
    id: '/integrations/media-preprocessing',
    path: '/integrations/media-preprocessing',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthConversationsNewRoute = AuthConversationsNewRouteImport.update({
  id: '/conversations/new',
  path: '/conversations/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContactsNewRoute = AuthContactsNewRouteImport.update({
  id: '/contacts/new',
  path: '/contacts/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContactsContactIdRoute = AuthContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsNewRoute = AuthAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsAgentIdRoute = AuthAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsWebhooksIndexRoute =
  AuthSettingsWebhooksIndexRouteImport.update({
    id: '/settings/webhooks/',
    path: '/settings/webhooks/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsOrganizationIndexRoute =
  AuthSettingsOrganizationIndexRouteImport.update({
    id: '/settings/organization/',
    path: '/settings/organization/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsMembersIndexRoute =
  AuthSettingsMembersIndexRouteImport.update({
    id: '/settings/members/',
    path: '/settings/members/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsApiKeysIndexRoute =
  AuthSettingsApiKeysIndexRouteImport.update({
    id: '/settings/api-keys/',
    path: '/settings/api-keys/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappIndexRoute =
  AuthIntegrationsWhatsappIndexRouteImport.update({
    id: '/integrations/whatsapp/',
    path: '/integrations/whatsapp/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsWebhooksNewRoute = AuthSettingsWebhooksNewRouteImport.update({
  id: '/settings/webhooks/new',
  path: '/settings/webhooks/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsWebhooksWebhookIdRoute =
  AuthSettingsWebhooksWebhookIdRouteImport.update({
    id: '/settings/webhooks/$webhookId',
    path: '/settings/webhooks/$webhookId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsOrganizationNewRoute =
  AuthSettingsOrganizationNewRouteImport.update({
    id: '/settings/organization/new',
    path: '/settings/organization/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsMembersNewRoute = AuthSettingsMembersNewRouteImport.update({
  id: '/settings/members/new',
  path: '/settings/members/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsMembersMemberIdRoute =
  AuthSettingsMembersMemberIdRouteImport.update({
    id: '/settings/members/$memberId',
    path: '/settings/members/$memberId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsApiKeysNewRoute = AuthSettingsApiKeysNewRouteImport.update({
  id: '/settings/api-keys/new',
  path: '/settings/api-keys/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsApiKeysApiKeyIdRoute =
  AuthSettingsApiKeysApiKeyIdRouteImport.update({
    id: '/settings/api-keys/$apiKeyId',
    path: '/settings/api-keys/$apiKeyId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappNewRoute =
  AuthIntegrationsWhatsappNewRouteImport.update({
    id: '/integrations/whatsapp/new',
    path: '/integrations/whatsapp/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappOrgAddressIdRoute =
  AuthIntegrationsWhatsappOrgAddressIdRouteImport.update({
    id: '/integrations/whatsapp/$orgAddressId',
    path: '/integrations/whatsapp/$orgAddressId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/': typeof AuthIndexRoute
  '/agents/$agentId': typeof AuthAgentsAgentIdRoute
  '/agents/new': typeof AuthAgentsNewRoute
  '/contacts/$contactId': typeof AuthContactsContactIdRoute
  '/contacts/new': typeof AuthContactsNewRoute
  '/conversations/new': typeof AuthConversationsNewRoute
  '/integrations/media-preprocessing': typeof AuthIntegrationsMediaPreprocessingRoute
  '/agents': typeof AuthAgentsIndexRoute
  '/contacts': typeof AuthContactsIndexRoute
  '/conversations': typeof AuthConversationsIndexRoute
  '/integrations': typeof AuthIntegrationsIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/integrations/whatsapp/$orgAddressId': typeof AuthIntegrationsWhatsappOrgAddressIdRoute
  '/integrations/whatsapp/new': typeof AuthIntegrationsWhatsappNewRoute
  '/settings/api-keys/$apiKeyId': typeof AuthSettingsApiKeysApiKeyIdRoute
  '/settings/api-keys/new': typeof AuthSettingsApiKeysNewRoute
  '/settings/members/$memberId': typeof AuthSettingsMembersMemberIdRoute
  '/settings/members/new': typeof AuthSettingsMembersNewRoute
  '/settings/organization/new': typeof AuthSettingsOrganizationNewRoute
  '/settings/webhooks/$webhookId': typeof AuthSettingsWebhooksWebhookIdRoute
  '/settings/webhooks/new': typeof AuthSettingsWebhooksNewRoute
  '/integrations/whatsapp': typeof AuthIntegrationsWhatsappIndexRoute
  '/settings/api-keys': typeof AuthSettingsApiKeysIndexRoute
  '/settings/members': typeof AuthSettingsMembersIndexRoute
  '/settings/organization': typeof AuthSettingsOrganizationIndexRoute
  '/settings/webhooks': typeof AuthSettingsWebhooksIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/': typeof AuthIndexRoute
  '/agents/$agentId': typeof AuthAgentsAgentIdRoute
  '/agents/new': typeof AuthAgentsNewRoute
  '/contacts/$contactId': typeof AuthContactsContactIdRoute
  '/contacts/new': typeof AuthContactsNewRoute
  '/conversations/new': typeof AuthConversationsNewRoute
  '/integrations/media-preprocessing': typeof AuthIntegrationsMediaPreprocessingRoute
  '/agents': typeof AuthAgentsIndexRoute
  '/contacts': typeof AuthContactsIndexRoute
  '/conversations': typeof AuthConversationsIndexRoute
  '/integrations': typeof AuthIntegrationsIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/integrations/whatsapp/$orgAddressId': typeof AuthIntegrationsWhatsappOrgAddressIdRoute
  '/integrations/whatsapp/new': typeof AuthIntegrationsWhatsappNewRoute
  '/settings/api-keys/$apiKeyId': typeof AuthSettingsApiKeysApiKeyIdRoute
  '/settings/api-keys/new': typeof AuthSettingsApiKeysNewRoute
  '/settings/members/$memberId': typeof AuthSettingsMembersMemberIdRoute
  '/settings/members/new': typeof AuthSettingsMembersNewRoute
  '/settings/organization/new': typeof AuthSettingsOrganizationNewRoute
  '/settings/webhooks/$webhookId': typeof AuthSettingsWebhooksWebhookIdRoute
  '/settings/webhooks/new': typeof AuthSettingsWebhooksNewRoute
  '/integrations/whatsapp': typeof AuthIntegrationsWhatsappIndexRoute
  '/settings/api-keys': typeof AuthSettingsApiKeysIndexRoute
  '/settings/members': typeof AuthSettingsMembersIndexRoute
  '/settings/organization': typeof AuthSettingsOrganizationIndexRoute
  '/settings/webhooks': typeof AuthSettingsWebhooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/agents/$agentId': typeof AuthAgentsAgentIdRoute
  '/_auth/agents/new': typeof AuthAgentsNewRoute
  '/_auth/contacts/$contactId': typeof AuthContactsContactIdRoute
  '/_auth/contacts/new': typeof AuthContactsNewRoute
  '/_auth/conversations/new': typeof AuthConversationsNewRoute
  '/_auth/integrations/media-preprocessing': typeof AuthIntegrationsMediaPreprocessingRoute
  '/_auth/agents/': typeof AuthAgentsIndexRoute
  '/_auth/contacts/': typeof AuthContactsIndexRoute
  '/_auth/conversations/': typeof AuthConversationsIndexRoute
  '/_auth/integrations/': typeof AuthIntegrationsIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/integrations/whatsapp/$orgAddressId': typeof AuthIntegrationsWhatsappOrgAddressIdRoute
  '/_auth/integrations/whatsapp/new': typeof AuthIntegrationsWhatsappNewRoute
  '/_auth/settings/api-keys/$apiKeyId': typeof AuthSettingsApiKeysApiKeyIdRoute
  '/_auth/settings/api-keys/new': typeof AuthSettingsApiKeysNewRoute
  '/_auth/settings/members/$memberId': typeof AuthSettingsMembersMemberIdRoute
  '/_auth/settings/members/new': typeof AuthSettingsMembersNewRoute
  '/_auth/settings/organization/new': typeof AuthSettingsOrganizationNewRoute
  '/_auth/settings/webhooks/$webhookId': typeof AuthSettingsWebhooksWebhookIdRoute
  '/_auth/settings/webhooks/new': typeof AuthSettingsWebhooksNewRoute
  '/_auth/integrations/whatsapp/': typeof AuthIntegrationsWhatsappIndexRoute
  '/_auth/settings/api-keys/': typeof AuthSettingsApiKeysIndexRoute
  '/_auth/settings/members/': typeof AuthSettingsMembersIndexRoute
  '/_auth/settings/organization/': typeof AuthSettingsOrganizationIndexRoute
  '/_auth/settings/webhooks/': typeof AuthSettingsWebhooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/oauth/callback'
    | '/'
    | '/agents/$agentId'
    | '/agents/new'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/conversations/new'
    | '/integrations/media-preprocessing'
    | '/agents'
    | '/contacts'
    | '/conversations'
    | '/integrations'
    | '/settings'
    | '/integrations/whatsapp/$orgAddressId'
    | '/integrations/whatsapp/new'
    | '/settings/api-keys/$apiKeyId'
    | '/settings/api-keys/new'
    | '/settings/members/$memberId'
    | '/settings/members/new'
    | '/settings/organization/new'
    | '/settings/webhooks/$webhookId'
    | '/settings/webhooks/new'
    | '/integrations/whatsapp'
    | '/settings/api-keys'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/webhooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/oauth/callback'
    | '/'
    | '/agents/$agentId'
    | '/agents/new'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/conversations/new'
    | '/integrations/media-preprocessing'
    | '/agents'
    | '/contacts'
    | '/conversations'
    | '/integrations'
    | '/settings'
    | '/integrations/whatsapp/$orgAddressId'
    | '/integrations/whatsapp/new'
    | '/settings/api-keys/$apiKeyId'
    | '/settings/api-keys/new'
    | '/settings/members/$memberId'
    | '/settings/members/new'
    | '/settings/organization/new'
    | '/settings/webhooks/$webhookId'
    | '/settings/webhooks/new'
    | '/integrations/whatsapp'
    | '/settings/api-keys'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/webhooks'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/oauth/callback'
    | '/_auth/'
    | '/_auth/agents/$agentId'
    | '/_auth/agents/new'
    | '/_auth/contacts/$contactId'
    | '/_auth/contacts/new'
    | '/_auth/conversations/new'
    | '/_auth/integrations/media-preprocessing'
    | '/_auth/agents/'
    | '/_auth/contacts/'
    | '/_auth/conversations/'
    | '/_auth/integrations/'
    | '/_auth/settings/'
    | '/_auth/integrations/whatsapp/$orgAddressId'
    | '/_auth/integrations/whatsapp/new'
    | '/_auth/settings/api-keys/$apiKeyId'
    | '/_auth/settings/api-keys/new'
    | '/_auth/settings/members/$memberId'
    | '/_auth/settings/members/new'
    | '/_auth/settings/organization/new'
    | '/_auth/settings/webhooks/$webhookId'
    | '/_auth/settings/webhooks/new'
    | '/_auth/integrations/whatsapp/'
    | '/_auth/settings/api-keys/'
    | '/_auth/settings/members/'
    | '/_auth/settings/organization/'
    | '/_auth/settings/webhooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/': {
      id: '/_auth/integrations/'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthIntegrationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/conversations/': {
      id: '/_auth/conversations/'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthConversationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contacts/': {
      id: '/_auth/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthContactsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/': {
      id: '/_auth/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthAgentsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/media-preprocessing': {
      id: '/_auth/integrations/media-preprocessing'
      path: '/integrations/media-preprocessing'
      fullPath: '/integrations/media-preprocessing'
      preLoaderRoute: typeof AuthIntegrationsMediaPreprocessingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/conversations/new': {
      id: '/_auth/conversations/new'
      path: '/conversations/new'
      fullPath: '/conversations/new'
      preLoaderRoute: typeof AuthConversationsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contacts/new': {
      id: '/_auth/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof AuthContactsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contacts/$contactId': {
      id: '/_auth/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AuthContactsContactIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/new': {
      id: '/_auth/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthAgentsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/$agentId': {
      id: '/_auth/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthAgentsAgentIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/webhooks/': {
      id: '/_auth/settings/webhooks/'
      path: '/settings/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof AuthSettingsWebhooksIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/organization/': {
      id: '/_auth/settings/organization/'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthSettingsOrganizationIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/members/': {
      id: '/_auth/settings/members/'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthSettingsMembersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/api-keys/': {
      id: '/_auth/settings/api-keys/'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthSettingsApiKeysIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/': {
      id: '/_auth/integrations/whatsapp/'
      path: '/integrations/whatsapp'
      fullPath: '/integrations/whatsapp'
      preLoaderRoute: typeof AuthIntegrationsWhatsappIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/webhooks/new': {
      id: '/_auth/settings/webhooks/new'
      path: '/settings/webhooks/new'
      fullPath: '/settings/webhooks/new'
      preLoaderRoute: typeof AuthSettingsWebhooksNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/webhooks/$webhookId': {
      id: '/_auth/settings/webhooks/$webhookId'
      path: '/settings/webhooks/$webhookId'
      fullPath: '/settings/webhooks/$webhookId'
      preLoaderRoute: typeof AuthSettingsWebhooksWebhookIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/organization/new': {
      id: '/_auth/settings/organization/new'
      path: '/settings/organization/new'
      fullPath: '/settings/organization/new'
      preLoaderRoute: typeof AuthSettingsOrganizationNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/members/new': {
      id: '/_auth/settings/members/new'
      path: '/settings/members/new'
      fullPath: '/settings/members/new'
      preLoaderRoute: typeof AuthSettingsMembersNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/members/$memberId': {
      id: '/_auth/settings/members/$memberId'
      path: '/settings/members/$memberId'
      fullPath: '/settings/members/$memberId'
      preLoaderRoute: typeof AuthSettingsMembersMemberIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/api-keys/new': {
      id: '/_auth/settings/api-keys/new'
      path: '/settings/api-keys/new'
      fullPath: '/settings/api-keys/new'
      preLoaderRoute: typeof AuthSettingsApiKeysNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/api-keys/$apiKeyId': {
      id: '/_auth/settings/api-keys/$apiKeyId'
      path: '/settings/api-keys/$apiKeyId'
      fullPath: '/settings/api-keys/$apiKeyId'
      preLoaderRoute: typeof AuthSettingsApiKeysApiKeyIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/new': {
      id: '/_auth/integrations/whatsapp/new'
      path: '/integrations/whatsapp/new'
      fullPath: '/integrations/whatsapp/new'
      preLoaderRoute: typeof AuthIntegrationsWhatsappNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/$orgAddressId': {
      id: '/_auth/integrations/whatsapp/$orgAddressId'
      path: '/integrations/whatsapp/$orgAddressId'
      fullPath: '/integrations/whatsapp/$orgAddressId'
      preLoaderRoute: typeof AuthIntegrationsWhatsappOrgAddressIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAgentsAgentIdRoute: typeof AuthAgentsAgentIdRoute
  AuthAgentsNewRoute: typeof AuthAgentsNewRoute
  AuthContactsContactIdRoute: typeof AuthContactsContactIdRoute
  AuthContactsNewRoute: typeof AuthContactsNewRoute
  AuthConversationsNewRoute: typeof AuthConversationsNewRoute
  AuthIntegrationsMediaPreprocessingRoute: typeof AuthIntegrationsMediaPreprocessingRoute
  AuthAgentsIndexRoute: typeof AuthAgentsIndexRoute
  AuthContactsIndexRoute: typeof AuthContactsIndexRoute
  AuthConversationsIndexRoute: typeof AuthConversationsIndexRoute
  AuthIntegrationsIndexRoute: typeof AuthIntegrationsIndexRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
  AuthIntegrationsWhatsappOrgAddressIdRoute: typeof AuthIntegrationsWhatsappOrgAddressIdRoute
  AuthIntegrationsWhatsappNewRoute: typeof AuthIntegrationsWhatsappNewRoute
  AuthSettingsApiKeysApiKeyIdRoute: typeof AuthSettingsApiKeysApiKeyIdRoute
  AuthSettingsApiKeysNewRoute: typeof AuthSettingsApiKeysNewRoute
  AuthSettingsMembersMemberIdRoute: typeof AuthSettingsMembersMemberIdRoute
  AuthSettingsMembersNewRoute: typeof AuthSettingsMembersNewRoute
  AuthSettingsOrganizationNewRoute: typeof AuthSettingsOrganizationNewRoute
  AuthSettingsWebhooksWebhookIdRoute: typeof AuthSettingsWebhooksWebhookIdRoute
  AuthSettingsWebhooksNewRoute: typeof AuthSettingsWebhooksNewRoute
  AuthIntegrationsWhatsappIndexRoute: typeof AuthIntegrationsWhatsappIndexRoute
  AuthSettingsApiKeysIndexRoute: typeof AuthSettingsApiKeysIndexRoute
  AuthSettingsMembersIndexRoute: typeof AuthSettingsMembersIndexRoute
  AuthSettingsOrganizationIndexRoute: typeof AuthSettingsOrganizationIndexRoute
  AuthSettingsWebhooksIndexRoute: typeof AuthSettingsWebhooksIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthAgentsAgentIdRoute: AuthAgentsAgentIdRoute,
  AuthAgentsNewRoute: AuthAgentsNewRoute,
  AuthContactsContactIdRoute: AuthContactsContactIdRoute,
  AuthContactsNewRoute: AuthContactsNewRoute,
  AuthConversationsNewRoute: AuthConversationsNewRoute,
  AuthIntegrationsMediaPreprocessingRoute:
    AuthIntegrationsMediaPreprocessingRoute,
  AuthAgentsIndexRoute: AuthAgentsIndexRoute,
  AuthContactsIndexRoute: AuthContactsIndexRoute,
  AuthConversationsIndexRoute: AuthConversationsIndexRoute,
  AuthIntegrationsIndexRoute: AuthIntegrationsIndexRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
  AuthIntegrationsWhatsappOrgAddressIdRoute:
    AuthIntegrationsWhatsappOrgAddressIdRoute,
  AuthIntegrationsWhatsappNewRoute: AuthIntegrationsWhatsappNewRoute,
  AuthSettingsApiKeysApiKeyIdRoute: AuthSettingsApiKeysApiKeyIdRoute,
  AuthSettingsApiKeysNewRoute: AuthSettingsApiKeysNewRoute,
  AuthSettingsMembersMemberIdRoute: AuthSettingsMembersMemberIdRoute,
  AuthSettingsMembersNewRoute: AuthSettingsMembersNewRoute,
  AuthSettingsOrganizationNewRoute: AuthSettingsOrganizationNewRoute,
  AuthSettingsWebhooksWebhookIdRoute: AuthSettingsWebhooksWebhookIdRoute,
  AuthSettingsWebhooksNewRoute: AuthSettingsWebhooksNewRoute,
  AuthIntegrationsWhatsappIndexRoute: AuthIntegrationsWhatsappIndexRoute,
  AuthSettingsApiKeysIndexRoute: AuthSettingsApiKeysIndexRoute,
  AuthSettingsMembersIndexRoute: AuthSettingsMembersIndexRoute,
  AuthSettingsOrganizationIndexRoute: AuthSettingsOrganizationIndexRoute,
  AuthSettingsWebhooksIndexRoute: AuthSettingsWebhooksIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
