/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthOrganizationsRouteImport } from './routes/_auth/organizations'
import { Route as AuthIntegrationsRouteImport } from './routes/_auth/integrations'
import { Route as AuthAgentsRouteImport } from './routes/_auth/agents'
import { Route as AuthConversationsIndexRouteImport } from './routes/_auth/conversations/index'
import { Route as AuthConversationsNewRouteImport } from './routes/_auth/conversations/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrganizationsRoute = AuthOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIntegrationsRoute = AuthIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsRoute = AuthAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConversationsIndexRoute = AuthConversationsIndexRouteImport.update({
  id: '/conversations/',
  path: '/conversations/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConversationsNewRoute = AuthConversationsNewRouteImport.update({
  id: '/conversations/new',
  path: '/conversations/new',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/agents': typeof AuthAgentsRoute
  '/integrations': typeof AuthIntegrationsRoute
  '/organizations': typeof AuthOrganizationsRoute
  '/settings': typeof AuthSettingsRoute
  '/': typeof AuthIndexRoute
  '/conversations/new': typeof AuthConversationsNewRoute
  '/conversations': typeof AuthConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/agents': typeof AuthAgentsRoute
  '/integrations': typeof AuthIntegrationsRoute
  '/organizations': typeof AuthOrganizationsRoute
  '/settings': typeof AuthSettingsRoute
  '/': typeof AuthIndexRoute
  '/conversations/new': typeof AuthConversationsNewRoute
  '/conversations': typeof AuthConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/agents': typeof AuthAgentsRoute
  '/_auth/integrations': typeof AuthIntegrationsRoute
  '/_auth/organizations': typeof AuthOrganizationsRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/conversations/new': typeof AuthConversationsNewRoute
  '/_auth/conversations/': typeof AuthConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/agents'
    | '/integrations'
    | '/organizations'
    | '/settings'
    | '/'
    | '/conversations/new'
    | '/conversations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/agents'
    | '/integrations'
    | '/organizations'
    | '/settings'
    | '/'
    | '/conversations/new'
    | '/conversations'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/agents'
    | '/_auth/integrations'
    | '/_auth/organizations'
    | '/_auth/settings'
    | '/_auth/'
    | '/_auth/conversations/new'
    | '/_auth/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organizations': {
      id: '/_auth/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthOrganizationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations': {
      id: '/_auth/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthIntegrationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents': {
      id: '/_auth/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthAgentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/conversations/': {
      id: '/_auth/conversations/'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthConversationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/conversations/new': {
      id: '/_auth/conversations/new'
      path: '/conversations/new'
      fullPath: '/conversations/new'
      preLoaderRoute: typeof AuthConversationsNewRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAgentsRoute: typeof AuthAgentsRoute
  AuthIntegrationsRoute: typeof AuthIntegrationsRoute
  AuthOrganizationsRoute: typeof AuthOrganizationsRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthConversationsNewRoute: typeof AuthConversationsNewRoute
  AuthConversationsIndexRoute: typeof AuthConversationsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAgentsRoute: AuthAgentsRoute,
  AuthIntegrationsRoute: AuthIntegrationsRoute,
  AuthOrganizationsRoute: AuthOrganizationsRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthConversationsNewRoute: AuthConversationsNewRoute,
  AuthConversationsIndexRoute: AuthConversationsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
